server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name 194.147.78.106 _;

    return 301 https://194-147-78-106.sslip.io$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name 194-147-78-106.sslip.io;

    root /var/www/interier;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /health {
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }
}
